### ISSUE TITLE
[FIX] ClipBoard Null 에러처리

### ISSUE THREAD

**Issue by ny2060** [TeamHavit/Havit-Android#407]
**📝 DESCRIPTION**
- Date : 2022.03.19

**☑ TODO**
- [FIX] ClipBoard Null 에러처리

**Comment by KxxHyoRim** [comment]
선생님 ㅋㅋㅋㅋㅋ 이슈 초큼만 더 구체적으루...

**Comment by ny2060** [comment]
> 선생님 ㅋㅋㅋㅋㅋ 이슈 초큼만 더 구체적으루...

넵!!! 다음부터 신경써서 만들도록 할게요!!
