### ISSUE TITLE
[FEAT] 카카오 로그인 SignUp Api 연동 및 자동 로그인 구현

### ISSUE THREAD

**Issue by ny2060** [TeamHavit/Havit-Android#551]
**📝 DESCRIPTION**
- Date : 2022.05.16

**☑ TODO**
- [FEAT] 카카오 로그인 SignUp Api 연동 및 자동 로그인 구현

**Comment by KxxHyoRim** [comment]
issue에 제목이랑 내용이랑 같으면.. 정확히 어떻게 구현을 했는지 파악하기가 어렵군요..
이럴거면 그냥 commit 메세지만 갈기지 .. 이게 뭐죠 ㅠㅠ
다음부터 더 신경써주세요..흘ㄺ흙...
