### ISSUE TITLE
[UI] ToastUtil - toast_text.xml padding 변경

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#602]
**📝 DESCRIPTION**
- Date : 2022.06.19

**☑ TODO**
- 기존 좌우 padding이 55dp였는데 40dp로 변경
- 아래 뷰에서 padding 값이 55dp 일경우 줄바꿈이 일어남
- 혹시 본인 뷰에서 문제있으면 알려주세요! @ny2060 @yubinquitous @sdu07024 

![image](https://user-images.githubusercontent.com/59546818/174480330-99846998-36a3-4d87-9abc-aee25c8a5b36.png)

아래 이미지는 마진만 변경했다는.. 어필..?
![image](https://user-images.githubusercontent.com/59546818/174480290-0c98d0b7-95fd-4e50-9e07-38c8a5ad2031.png)

**Comment by yubinquitous** [comment]
문제 없습니당~~👍
