### ISSUE TITLE
[FEAT] 회원가입/로그인 시 유효한 fcm token으로 서버통신

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#642]
**📝 DESCRIPTION**
- Date : 2022.07.28
- 기존에 회원가입/로그인 시 null 값으로 통신을 했었음
- 해빗 push server에 몽고id가 안만들어짐
- 유효한 fcm token을 사용할 수 있도록 코드를 추가함

**☑ TODO**
- `AuthRepository`, `SignInViewModel `수정

**Comment by KxxHyoRim** [comment]
@ny2060  여기 로직 내가 수정했어!
그리고 다른 얘기긴 하지만 `SignInViewModel `안에 회원가입, 로그인 로직이 다 들어가있는거 같은데
`SignViewModel`로 파일명 수정하는건 어때?

**Comment by ny2060** [comment]
> @ny2060 여기 로직 내가 수정했어! 그리고 다른 얘기긴 하지만 `SignInViewModel `안에 회원가입, 로그인 로직이 다 들어가있는거 같은데 `SignViewModel`로 파일명 수정하는건 어때?

오케이 ~ 수정할게!!

**Comment by KxxHyoRim** [comment]
굳👍
