### ISSUE TITLE
[FEAT,UI] 디자인 QA 반영

### ISSUE THREAD

**Issue by ny2060** [TeamHavit/Havit-Android#663]
**📝 DESCRIPTION**
- Date : 2022.08.08

**☑ TODO**
- [FEAT] 서비스 이용 및 이용약관 동의 토글 로직 수정
- [UI] 마이페이지 전체 카테고리 뒤로가기 버튼 추가

**Comment by KxxHyoRim** [comment]
나영아 이거 다 됐으면 close 해줘~~
