### ISSUE TITLE
[FIX/FEAT] 2차 디자인 QA 반영

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#666]
**📝 DESCRIPTION**
- Date : 2022.08.10

**☑ TODO**
- [x] fix: 콘텐츠 뷰 - 수정 버튼 이벤트 x 현상 해결

**Comment by KxxHyoRim** [comment]
이거 새로고침 로직 빠졌으니까 '수정' 안눌러지는거 머지해주라!
