### ISSUE TITLE
[FIX] 회원탈퇴완료 Dialog onDestroyView -> 로그인 화면으로 연결 

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#818]
**📝 DESCRIPTION**
- Date : 2022.03.01

- **Before** 
    - 회원탈퇴 다이얼로그에서 close 버튼, 확인 버튼 눌렀을 때만 `doAfterConfirm()`연결되어 있었음
    - 탈퇴 다이얼로그가 떠있는 상태에서 background를 눌러서 `onDestroyView()` 가 될때, 
    로직상으로는 회원탈퇴가 되었음에도 불구하고 회원탈퇴 화면에 머물러 있음

- **AFTER**
    - 회원탈퇴dialog 의 `onDestroyView()` 일 경우 `doAfterConfirm()`을 실행
    
    ```kotlin
  override fun onDestroyView() {
        if (dialogMode == UNREGISTER) {
            doAfterConfirm()
        }
        super.onDestroyView()
        _binding = null
  }
    ```

**Comment by KxxHyoRim** [comment]
@yubinquitous 유빈아 이거 확인해줘!

**Comment by yubinquitous** [comment]
화긴완!! 고마웡😆
