### ISSUE TITLE
[UI] Placeholder Dummy 이미지 교체

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#839]
## **📝 DESCRIPTION**
- Date : 2022.04.26
- 아래 이미지를 보면 kakao Brain 콘텐츠의 이미지만 다르게 표시됨
![image](https://user-images.githubusercontent.com/59546818/234355291-9474b689-e508-4ef8-b8c5-fddc6c38ed71.png)

## ⚠️ 에러 원인
https://kakaobrain-pathfinder2.com/
이 링크는 이상한 링크입니다.
바로 메타데이터 이미지가 
`“./@resources/images/kakaobrain_og_new.png”`
이렇게 생겨먹은 친구이죠.
즉, 정상적인 링크가 아닌데 정상적인 링크인 척을 하는 친구입니다.

오작동 로직은 다음과 같습니다.
1. 콘텐츠 저장시 클라에서 이상한 string을 보낸다 "./@resources.. "
2. 서버에서는 imageUrl가 빈값이 아니라고 판단한다. 
3. 즉, dummy 이미지를 보내지 않고, "./@resources.. " 를 도로 보내준다
4. 안드에서 처리할수 없는 이미지인 경우 `img_contents_dumm_1`(정사각형) 이미지를 보여준다.
5. item의 ImageView는 직사각형인데 정사각형 이미지를 placeHolder로 설정해둬서, 해상도가 안맞는 문제입니다.

## **☑ TODO**
- placeholder 이미지 `img_contents_dumm_1` 에서 `img_contents_dumm_3` 으로 변경
(정사각형 -> 직사각형)
- BindingAdapter 다른 뷰에서는 문제되지 않는지 확인하기 (ex. 최근저장콘텐츠 Activity)

**Comment by KxxHyoRim** [comment]
# 수정 전 1. scale 문제
- 문제 : '팀네이버 신입 공채' 콘텐츠의 **좌우 여백**
- 해결 : scaleType 지정
<img width="300" src="https://user-images.githubusercontent.com/59546818/235895246-94d4910e-2756-4384-a16e-1ba7118f683c.png">

# 수정 전 2. radius 문제
- 문제 : 실제 이미지가 있는 imageView 의 radius랑 placeholder의 radius가 다름
- 해결 : sytle.xml을 활용해 placeholder에도 radius 4dp 지정해둠
<img width="300" alt="image" src="https://user-images.githubusercontent.com/59546818/235897355-1a7acd92-5c6b-4f03-afc1-87880209a6f8.png">

# 수정 후
<img width="300" alt="image" src="https://user-images.githubusercontent.com/59546818/235898517-38e11ab7-61c9-4958-9786-e877a6da5546.png">

**Comment by KxxHyoRim** [comment]
@kimhyeing 위 문제두개도 고쳐뒀습니다! 확인부탁~

**Comment by kimhyeing** [comment]
아하 확인했습니다!!!!! 감사합니당 ㅎㅎ
