### ISSUE TITLE
[FEAT] 커뮤니티 삭제 다이얼로그 제작

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#943]
**📝 DESCRIPTION**
- Date : 2024.06.17

**☑ TODO**
- [x] 커뮤니티 삭제 다이얼로그 제작
- [x] `isAuthor` 값에 따라 삭제 or 신고 다이얼로그 띄우기

**Comment by KxxHyoRim** [comment]
혜인! 이부분 커뮤니티 상세 조회 화면에서는 내가 쓴 게시물도 '삭제하기'가 아니라 '신고하기'로 표시되는것 같은데 이거 확인부탁해!
